# Generated by Django 3.1.7 on 2021-03-11 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=256, unique=True, verbose_name='用户id')),
                ('userName', models.CharField(max_length=256, verbose_name='用户名')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
    ]
