# Generated by Django 3.1.7 on 2021-03-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertitle',
            name='cityName',
            field=models.CharField(default='未知', max_length=32, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='fan',
            field=models.CharField(default='-1', max_length=32, verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='follow',
            field=models.CharField(default='-1', max_length=32, verbose_name='关注的数量'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='gender',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='ksID',
            field=models.CharField(default='xxxxxxxxxxxxxx', max_length=128, verbose_name='快手id'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='photo',
            field=models.CharField(default='-1', max_length=32, verbose_name='作品数量'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='stateUser',
            field=models.IntegerField(choices=[(0, '初次爬取'), (1, '测试')], default=0, verbose_name='用户信息状态'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='userImg',
            field=models.CharField(default='https://tx2.a.yximgs.com/uhead/AB/2020/08/17/09/BMjAyMDA4MTcwOTM2MDNfMjQ0NzAyMDZfMV9oZDM4Nl8xODU=_s.jpg', max_length=256, verbose_name='图片地址'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='user_text',
            field=models.CharField(default='xxxxxxxxxxxxx', max_length=2560, verbose_name='用户简述'),
        ),
        migrations.AddField(
            model_name='usertitle',
            name='xinzuo',
            field=models.CharField(default='未知', max_length=32, verbose_name='星座'),
        ),
    ]
