# Generated by Django 3.1.7 on 2021-03-13 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210312_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertitle',
            name='stateUser',
            field=models.IntegerField(choices=[(0, '初次爬取'), (1, 'ksVideo'), (2, 'ksLive'), (3, 'ksVideo+ksLive')], default=0, verbose_name='用户信息状态'),
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.CharField(default='xxxxxxxxxxxxxx', max_length=128, verbose_name='视频id')),
                ('caption', models.CharField(default='暂无', max_length=512, verbose_name='视频描述')),
                ('coversUrl', models.CharField(default='xxxxxxxxxxx', max_length=512, verbose_name='视频封面')),
                ('videoPath', models.CharField(default='xxxxxxxxxxxxx', max_length=512, verbose_name='视频地址')),
                ('realLikeCount', models.CharField(default='xxxxxxxxxxx', max_length=64, verbose_name='具体点赞数量')),
                ('animatedCoverUrl', models.CharField(default='xxxxxxxx', max_length=512, verbose_name='封面动画')),
                ('stateVideo', models.IntegerField(choices=[(1, '默认ksVideo'), (2, 'ksLive'), (3, 'ksVideo+ksLive')], default=1, verbose_name='状态')),
                ('displayView', models.CharField(default='-1', max_length=64, verbose_name='播放量')),
                ('displayComment', models.CharField(default='-1', max_length=64, verbose_name='评论数')),
                ('theUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.usertitle')),
            ],
        ),
    ]
