# Generated by Django 3.1.7 on 2021-03-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210313_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userphoto',
            old_name='theUser',
            new_name='thephotoUser',
        ),
    ]
